name: sCellST
channels:
  - bioconda
  - pytorch
  - pyg
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - aiohappyeyeballs=2.4.3
  - aiohttp=3.11.8
  - aiosignal=1.3.1
  - alsa-lib=1.2.13
  - anndata=0.10.9
  - annotated-types=0.7.0
  - anyio=4.8.0
  - aom=3.9.1
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arpack=3.9.1
  - array-api-compat=1.9.1
  - arrow=1.3.0
  - asciitree=0.3.3
  - asttokens=3.0.0
  - async-lru=2.0.4
  - async-timeout=5.0.1
  - atk-1.0=2.38.0
  - attr=2.5.1
  - attrs=24.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.0
  - aws-c-common=0.9.31
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.0
  - aws-c-io=0.15.0
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.0
  - aws-c-sdkutils=0.2.0
  - aws-checksums=0.2.0
  - aws-crt-cpp=0.29.0
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - bokeh=3.6.1
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.3
  - c-blosc2=2.15.1
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - cfitsio=4.4.1
  - charls=2.4.2
  - charset-normalizer=3.4.0
  - click=8.1.7
  - cloudpickle=3.1.0
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.2
  - contourpy=1.3.1
  - cpython=3.10.15
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.6
  - cycler=0.12.1
  - cytoolz=1.0.0
  - dask=2024.11.2
  - dask-core=2024.11.2
  - dask-expr=1.1.19
  - dask-image=2024.5.3
  - datasets=2.14.4
  - datashader=0.16.3
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.12
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.7
  - distributed=2024.11.2
  - docker-pycreds=0.4.0
  - docrep=0.3.2
  - double-conversion=3.3.0
  - einops=0.8.0
  - eval_type_backport=0.2.2
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fasteners=0.19
  - ffmpeg=7.1.0
  - fftw=3.3.10
  - filelock=3.16.1
  - folium=0.19.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.0
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freetype=2.12.1
  - freexl=2.0.0
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2023.6.0
  - gdk-pixbuf=2.42.12
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.13.0
  - geotiff=1.7.3
  - get-annotations=0.1.2
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - ghostscript=10.04.0
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.44
  - glib=2.82.2
  - glib-tools=2.82.2
  - glog=0.7.1
  - glpk=5.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.13
  - graphviz=12.0.0
  - grpcio=1.65.5
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - gtk2=2.24.33
  - gts=0.7.6
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.12.1
  - harfbuzz=9.0.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - huggingface_hub=0.26.2
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - igraph=0.10.15
  - imagecodecs=2024.9.22
  - imageio=2.36.1
  - imagemagick=7.1.1_41
  - imath=3.1.12
  - importlib-metadata=8.5.0
  - importlib_resources=6.5.2
  - inflect=7.5.0
  - ipykernel=6.29.5
  - ipython=8.32.0
  - isoduration=20.11.0
  - jasper=4.2.4
  - jbig=2.1
  - jedi=0.19.2
  - jinja2=3.1.4
  - joblib=1.4.2
  - json-c=0.18
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jxrlib=1.1
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - legacy-api-wrap=1.4.1
  - leidenalg=0.10.2
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarchive=3.7.7
  - libarrow=18.0.0
  - libarrow-acero=18.0.0
  - libarrow-dataset=18.0.0
  - libarrow-substrait=18.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.3
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.4
  - libclang13=19.1.4
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.11.1.6
  - libcups=2.3.3
  - libcurand=10.3.7.77
  - libcurl=8.10.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libde265=1.0.15
  - libdeflate=1.22
  - libdicom=1.0.5
  - libdrm=2.4.123
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexif=0.6.21
  - libexpat=2.6.4
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt=1.11.0
  - libgcrypt-devel=1.11.0
  - libgcrypt-lib=1.11.0
  - libgcrypt-tools=1.11.0
  - libgd=2.3.3
  - libgdal-core=3.10.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.30.0
  - libgoogle-cloud-storage=2.30.0
  - libgpg-error=1.51
  - libgrpc=1.65.5
  - libheif=1.18.2
  - libhwloc=2.11.1
  - libhwy=1.1.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libleidenalg=0.11.1
  - libllvm14=14.0.6
  - libllvm19=19.1.4
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libmatio=1.5.28
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libogg=1.3.5
  - libopenblas=0.3.28
  - libopencv=4.10.0
  - libopenvino=2024.4.0
  - libopenvino-auto-batch-plugin=2024.4.0
  - libopenvino-auto-plugin=2024.4.0
  - libopenvino-hetero-plugin=2024.4.0
  - libopenvino-intel-cpu-plugin=2024.4.0
  - libopenvino-intel-gpu-plugin=2024.4.0
  - libopenvino-intel-npu-plugin=2024.4.0
  - libopenvino-ir-frontend=2024.4.0
  - libopenvino-onnx-frontend=2024.4.0
  - libopenvino-paddle-frontend=2024.4.0
  - libopenvino-pytorch-frontend=2024.4.0
  - libopenvino-tensorflow-frontend=2024.4.0
  - libopenvino-tensorflow-lite-frontend=2024.4.0
  - libopus=1.3.1
  - libparquet=18.0.0
  - libpciaccess=0.18
  - libpng=1.6.44
  - libpq=16.6
  - libprotobuf=5.27.5
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - librttopo=1.1.0
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.47.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.7
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libudev1=256.7
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libva=2.22.0
  - libvips=8.16.0
  - libvorbis=1.3.7
  - libvpx=1.14.1
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.13.5
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - lightning=2.4.0
  - lightning-utilities=0.11.9
  - llvm-openmp=15.0.7
  - llvmlite=0.43.0
  - locket=1.0.0
  - loguru=0.7.2
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.8.1
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - matplotlib-scalebar=0.8.1
  - mdurl=0.1.2
  - minizip=4.0.7
  - mistune=3.1.1
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - more-itertools=10.5.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - multiprocess=0.70.15
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - natsort=8.4.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - nspr=4.36
  - nss=3.107
  - numba=0.60.0
  - numcodecs=0.13.1
  - ocl-icd=2.3.2
  - omnipath=1.0.8
  - opencl-headers=2024.10.24
  - opencv=4.10.0
  - openexr=3.2.2
  - openh264=2.5.0
  - openjpeg=2.5.2
  - openslide=4.0.0
  - openssl=3.4.1
  - orc=2.0.2
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - pango=1.54.0
  - parso=0.8.4
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.44
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pims=0.7
  - pip=24.3.1
  - pixman=0.43.2
  - pkg-config=0.29.2
  - pkgconfig=1.5.5
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - pooch=1.8.2
  - poppler=24.11.0
  - poppler-data=0.4.12
  - proj=9.5.1
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - propcache=0.2.0
  - protobuf=5.27.5
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.14
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - py-opencv=4.10.0
  - pyarrow=18.0.0
  - pyarrow-core=18.0.0
  - pycparser=2.22
  - pyct=0.5.0
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pyg=2.6.1
  - pynndescent=0.5.13
  - pyogrio=0.10.0
  - pyparsing=3.2.0
  - pyproj=3.7.0
  - pysocks=1.7.1
  - python=3.10.15
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-igraph=0.11.8
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python-xxhash=3.5.0
  - python_abi=3.10
  - pytorch=2.4.0
  - pytorch-cuda=11.8
  - pytorch-lightning=2.4.0
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.2
  - pytz=2024.1
  - pyvips=2.2.3
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - qhull=2020.2
  - qt-main=5.15.15
  - qt6-main=6.7.3
  - rav1e=0.6.6
  - rdma-core=54.0
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - regex=2024.11.6
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.22.3
  - s2n=1.5.6
  - safetensors=0.4.5
  - scanpy=1.10.3
  - scikit-learn=1.5.2
  - scikit-learn-extra=0.2.0
  - scikit-misc=0.1.4
  - scipy=1.14.1
  - scprep=1.2.3
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - sentry-sdk=2.20.0
  - session-info=1.0.0
  - setproctitle=1.3.4
  - setuptools=75.6.0
  - shapely=2.0.6
  - six=1.16.0
  - slicerator=1.1.0
  - smmap=5.0.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - sqlite=3.47.0
  - squidpy=1.2.2
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - stdlib-list=0.11.0
  - submitit=1.5.2
  - svt-av1=2.3.0
  - sympy=1.13.3
  - tbb=2021.13.0
  - tblib=3.0.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - terminado=0.18.1
  - texttable=1.7.0
  - threadpoolctl=3.5.0
  - timm=1.0.11
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenizers=0.20.4
  - tomli=2.2.1
  - toolz=1.0.0
  - torchmetrics=1.5.2
  - torchtriton=3.0.0
  - torchvision=0.19.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.46.3
  - typeguard=4.4.1
  - types-python-dateutil=2.9.0.20241206
  - typing=3.10.0.0
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - ultralytics=8.3.38
  - umap-learn=0.5.7
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - validators=0.34.0
  - wandb=0.18.7
  - wayland=1.23.1
  - wayland-protocols=1.37
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.0
  - x264=1!164.3095
  - x265=3.5
  - xarray-datatree=0.0.14
  - xarray-schema=0.0.3
  - xarray-spatial=0.4.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.5
  - xkeyboard-config=2.43
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.11
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.5
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xorgproto=2024.1
  - xxhash=0.8.2
  - xyzservices=2024.9.0
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - yaml=0.2.5
  - yarl=1.18.0
  - zarr=2.18.3
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zlib-ng=2.2.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - affine==2.4.0
      - aiobotocore==2.5.4
      - aioitertools==0.12.0
      - albumentations==1.2.1
      - antlr4-python3-runtime==4.9.3
      - beautifulsoup4==4.12.3
      - biothings-client==0.3.1
      - blosc2==2.7.1
      - botocore==1.31.17
      - cellvit-light==0.0.5
      - click-plugins==1.1.1
      - cligj==0.7.2
      - einops-exts==0.0.4
      - gdown==5.2.0
      - geojson==3.2.0
      - hestcore==1.0.4
      - hydra-core==1.3.2
      - jmespath==1.0.1
      - multipledispatch==1.0.0
      - multiscale-spatial-image==2.0.2
      - mygene==3.2.2
      - ndindex==1.9.2
      - numexpr==2.10.2
      - numpy==1.26.2
      - ome-zarr==0.9.0
      - omegaconf==2.3.0
      - openslide-python==1.3.1
      - pandarallel==1.6.5
      - param==2.1.1
      - pygments==2.18.0
      - rasterio==1.4.3
      - s3fs==2023.6.0
      - scikit-image==0.24.0
      - soupsieve==2.6
      - spatial-image==1.1.0
      - spatialdata==0.2.6
      - tables==3.10.1
      - tensorboardx==2.6.2.2
      - tifffile==2024.9.20
      - timm-ctp==0.5.4
      - ujson==5.10.0
      - ultralytics-thop==2.0.12
      - urllib3==1.26.20
      - xarray==2024.11.0
      - xarray-dataclasses==1.8.0
