train_data_folder: ""
task_type: "regression"
device: "cuda"
model_type: "instance_mil"
seed: 0
loss: "mse"

preprocessing:
  normalize: true
  log1p: true
  filtering: true
  radius_ratio: 1.
  gene_to_pred: []
  gene_type: "HVG"
  n_genes: 1000

data:
  n_folds: 5
  batch_size: 128
  scale_labels: true
  dataset_type: "embedding"
  extraction_img_size: 12.
  tag_ssl:

trainer:
  lr: 1.e-4
  max_epoch: 1000
  patience: 20

embedder:
  archi: "resnet50"
  weights: "moco"

predictor:
  input_dim:
  hidden_dim: [256, 256, 256]
  output_dim: 1
  dispersion: "gene"
  final_activation: "softplus"
  dropout_rate: 0.1

model:
  aggregation_type: "mean"